---
title: "Sample-analysis"
author: "Ben"
date: "12/2/2018"
output: html_document
---


```{r libraries}
library(ggthemes)
library(tidyverse)
```

Data
```{r data}
dfEntropy <-read.csv(file.path(getwd(), "notebooks/data/entropies.csv"))
dfCEs <-read.csv(file.path(getwd(), "notebooks/data/ces.csv"))
```

```{r plot-entropies}
dfEntropy %>%
  ggplot(aes(x=date, y=ent, col=genre)) +
    geom_point(size=2, alpha=0.8) +
    geom_line(alpha=0.3) +
    geom_smooth(col='red') +
    xlab("Decade") +
    ylab("Unsmoothed unigram entropies") +
    ggtitle("Diachronic Entropy Measures in COHA corpus") +
    theme_few() +
    theme(plot.title=element_text(hjust=0.5))
```

```{r plot-cross-entropies}
dfCEs %>%
  mutate(pair=as.character(pair)) %>%
  rowwise %>%
  mutate(first=strsplit(pair, "-")[[1]][1],
         second=strsplit(pair, "-")[[1]][2]) %>%
  ggplot(aes(x=decade, y=ce, col=second)) +
    geom_point(size=2, alpha=0.8) +
    geom_line(alpha=0.3) +
    geom_smooth(col='red') + 
    xlab("Decade") +
    ylab("Smoothed unigram cross-entropies") +
    ggtitle("Diachronic Cross-entropy Measures \nby Genre in COHA corpus") +
    theme_few() +
    theme(plot.title=element_text(hjust=0.5)) +
    facet_grid(~first)
```




